build: presentation.tex
	pdflatex presentation
	pdflatex presentation
	pdflatex presentation
	evince presentation.pdf
clean:
	rm -r -f *.log *.out *.vrb *.snm *.aux *.nav *.toc *.bbl *.blg *.gz presentation.pdf *.spl
